DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(6) DEFAULT NULL,
  code3 varchar(6) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY code3 (code3)
);

INSERT INTO countries (id, code, code3, name) VALUES (1,'AF','AFG','Afghanistan');
INSERT INTO countries (id, code, code3, name) VALUES (2,'AL','ALB','Albania');
INSERT INTO countries (id, code, code3, name) VALUES (3,'DZ','DZA','Algeria');
INSERT INTO countries (id, code, code3, name) VALUES (4,'AS','ASM','American Samoa');
INSERT INTO countries (id, code, code3, name) VALUES (5,'AD','AND','Andorra');
INSERT INTO countries (id, code, code3, name) VALUES (6,'AO','AGO','Angola');
INSERT INTO countries (id, code, code3, name) VALUES (7,'AI','AIA','Anguilla');
INSERT INTO countries (id, code, code3, name) VALUES (8,'AR','ARG','Argentina');
INSERT INTO countries (id, code, code3, name) VALUES (9,'AA',NULL,'Armenia');
INSERT INTO countries (id, code, code3, name) VALUES (10,'AW','ABW','Aruba');
INSERT INTO countries (id, code, code3, name) VALUES (11,'AU','AUS','Australia');
INSERT INTO countries (id, code, code3, name) VALUES (12,'AT','AUT','Austria');
INSERT INTO countries (id, code, code3, name) VALUES (13,'AZ','AZE','Azerbaijan');
INSERT INTO countries (id, code, code3, name) VALUES (14,'BS','BHS','Bahamas');
INSERT INTO countries (id, code, code3, name) VALUES (15,'BH','BHR','Bahrain');
INSERT INTO countries (id, code, code3, name) VALUES (16,'BD','BGD','Bangladesh');
INSERT INTO countries (id, code, code3, name) VALUES (17,'BB','BRB','Barbados');
INSERT INTO countries (id, code, code3, name) VALUES (18,'BY','BLR','Belarus');
INSERT INTO countries (id, code, code3, name) VALUES (19,'BE','BEL','Belgium');
INSERT INTO countries (id, code, code3, name) VALUES (20,'BZ','BLZ','Belize');
INSERT INTO countries (id, code, code3, name) VALUES (21,'BJ','BEN','Benin');
INSERT INTO countries (id, code, code3, name) VALUES (22,'BM','BMU','Bermuda');
INSERT INTO countries (id, code, code3, name) VALUES (23,'BT','BTN','Bhutan');
INSERT INTO countries (id, code, code3, name) VALUES (24,'BO','BOL','Bolivia');
INSERT INTO countries (id, code, code3, name) VALUES (26,'BA','BIH','Bosnia &amp; Herzegovina');
INSERT INTO countries (id, code, code3, name) VALUES (27,'BW','BWA','Botswana');
INSERT INTO countries (id, code, code3, name) VALUES (28,'BR','BRA','Brazil');
INSERT INTO countries (id, code, code3, name) VALUES (29,'BC',NULL,'British Indian Ocean Ter');
INSERT INTO countries (id, code, code3, name) VALUES (30,'BN','BRN','Brunei');
INSERT INTO countries (id, code, code3, name) VALUES (31,'BG','BGR','Bulgaria');
INSERT INTO countries (id, code, code3, name) VALUES (32,'BF','BFA','Burkina Faso');
INSERT INTO countries (id, code, code3, name) VALUES (33,'BI','BDI','Burundi');
INSERT INTO countries (id, code, code3, name) VALUES (34,'KH','KHM','Cambodia');
INSERT INTO countries (id, code, code3, name) VALUES (35,'CM','CMR','Cameroon');
INSERT INTO countries (id, code, code3, name) VALUES (36,'CA','CAN','Canada');
INSERT INTO countries (id, code, code3, name) VALUES (37,'IC',NULL,'Canary Islands');
INSERT INTO countries (id, code, code3, name) VALUES (38,'CV','CPV','Cape Verde');
INSERT INTO countries (id, code, code3, name) VALUES (39,'KY','CYM','Cayman Islands');
INSERT INTO countries (id, code, code3, name) VALUES (40,'CF','CAF','Central African Republic');
INSERT INTO countries (id, code, code3, name) VALUES (41,'TD','TCD','Chad');
INSERT INTO countries (id, code, code3, name) VALUES (42,NULL,NULL,'Channel Islands');
INSERT INTO countries (id, code, code3, name) VALUES (43,'CL','CHL','Chile');
INSERT INTO countries (id, code, code3, name) VALUES (44,'CN','CHN','China');
INSERT INTO countries (id, code, code3, name) VALUES (45,'CX','CXR','Christmas Island');
INSERT INTO countries (id, code, code3, name) VALUES (46,'CS',NULL,'Cocos Island');
INSERT INTO countries (id, code, code3, name) VALUES (47,'CO','COL','Colombia');
INSERT INTO countries (id, code, code3, name) VALUES (48,'CC','CCK','Comoros');
INSERT INTO countries (id, code, code3, name) VALUES (49,'CG','COG','Congo');
INSERT INTO countries (id, code, code3, name) VALUES (50,'CK','COK','Cook Islands');
INSERT INTO countries (id, code, code3, name) VALUES (51,'CR','CRI','Costa Rica');
INSERT INTO countries (id, code, code3, name) VALUES (52,'CI','CIV','Ivory Coast');
INSERT INTO countries (id, code, code3, name) VALUES (53,'HR','HRV','Croatia');
INSERT INTO countries (id, code, code3, name) VALUES (54,'CU','CUB','Cuba');
INSERT INTO countries (id, code, code3, name) VALUES (55,'CB',NULL,'Curacao');
INSERT INTO countries (id, code, code3, name) VALUES (56,'CY','CYP','Cyprus');
INSERT INTO countries (id, code, code3, name) VALUES (57,'CZ','CZE','Czech Republic');
INSERT INTO countries (id, code, code3, name) VALUES (58,'DK','DNK','Denmark');
INSERT INTO countries (id, code, code3, name) VALUES (59,'DJ','DJI','Djibouti');
INSERT INTO countries (id, code, code3, name) VALUES (60,'DM','DMA','Dominica');
INSERT INTO countries (id, code, code3, name) VALUES (61,'DO','DOM','Dominican Republic');
INSERT INTO countries (id, code, code3, name) VALUES (62,'TM','TKM','East Timor');
INSERT INTO countries (id, code, code3, name) VALUES (63,'EC','ECU','Ecuador');
INSERT INTO countries (id, code, code3, name) VALUES (64,'EG','EGY','Egypt');
INSERT INTO countries (id, code, code3, name) VALUES (65,'SV','SLV','El Salvador');
INSERT INTO countries (id, code, code3, name) VALUES (66,'GQ','GNQ','Equatorial Guinea');
INSERT INTO countries (id, code, code3, name) VALUES (67,'ER','ERI','Eritrea');
INSERT INTO countries (id, code, code3, name) VALUES (68,'EE','EST','Estonia');
INSERT INTO countries (id, code, code3, name) VALUES (69,'ET','ETH','Ethiopia');
INSERT INTO countries (id, code, code3, name) VALUES (70,'FA',NULL,'Falkland Islands');
INSERT INTO countries (id, code, code3, name) VALUES (71,'FO','FRO','Faroe Islands');
INSERT INTO countries (id, code, code3, name) VALUES (72,'FJ','FJI','Fiji');
INSERT INTO countries (id, code, code3, name) VALUES (73,'FI','FIN','Finland');
INSERT INTO countries (id, code, code3, name) VALUES (74,'FR','FRA','France');
INSERT INTO countries (id, code, code3, name) VALUES (75,'GF','GUF','French Guiana');
INSERT INTO countries (id, code, code3, name) VALUES (76,'PF','PYF','French Polynesia');
INSERT INTO countries (id, code, code3, name) VALUES (77,'FS',NULL,'French Southern Ter');
INSERT INTO countries (id, code, code3, name) VALUES (78,'GA','GAB','Gabon');
INSERT INTO countries (id, code, code3, name) VALUES (79,'GM','GMB','Gambia');
INSERT INTO countries (id, code, code3, name) VALUES (80,'GE','GEO','Georgia');
INSERT INTO countries (id, code, code3, name) VALUES (81,'DE','DEU','Germany');
INSERT INTO countries (id, code, code3, name) VALUES (82,'GH','GHA','Ghana');
INSERT INTO countries (id, code, code3, name) VALUES (83,'GI','GIB','Gibraltar');
INSERT INTO countries (id, code, code3, name) VALUES (84,'GR','GRC','Greece');
INSERT INTO countries (id, code, code3, name) VALUES (85,'GL','GRL','Greenland');
INSERT INTO countries (id, code, code3, name) VALUES (86,'GD','GRD','Grenada');
INSERT INTO countries (id, code, code3, name) VALUES (87,'GP','GLP','Guadeloupe');
INSERT INTO countries (id, code, code3, name) VALUES (88,'GU','GUM','Guam');
INSERT INTO countries (id, code, code3, name) VALUES (89,'GT','GTM','Guatemala');
INSERT INTO countries (id, code, code3, name) VALUES (90,'GN','GIN','Guinea');
INSERT INTO countries (id, code, code3, name) VALUES (91,'GY','GUY','Guyana');
INSERT INTO countries (id, code, code3, name) VALUES (92,'HT','HTI','Haiti');
INSERT INTO countries (id, code, code3, name) VALUES (93,'HW',NULL,'Hawaii');
INSERT INTO countries (id, code, code3, name) VALUES (94,'HN','HND','Honduras');
INSERT INTO countries (id, code, code3, name) VALUES (95,'HK','HKG','Hong Kong');
INSERT INTO countries (id, code, code3, name) VALUES (96,'HU','HUN','Hungary');
INSERT INTO countries (id, code, code3, name) VALUES (97,'IS','ISL','Iceland');
INSERT INTO countries (id, code, code3, name) VALUES (98,'IN','IND','India');
INSERT INTO countries (id, code, code3, name) VALUES (99,'ID','IDN','Indonesia');
INSERT INTO countries (id, code, code3, name) VALUES (100,'IA',NULL,'Iran');
INSERT INTO countries (id, code, code3, name) VALUES (101,'IQ','IRQ','Iraq');
INSERT INTO countries (id, code, code3, name) VALUES (102,'IE','IRL','Ireland');
INSERT INTO countries (id, code, code3, name) VALUES (103,'IM','IMN','Isle of Man');
INSERT INTO countries (id, code, code3, name) VALUES (104,'IL','ISR','Israel');
INSERT INTO countries (id, code, code3, name) VALUES (105,'IT','ITA','Italy');
INSERT INTO countries (id, code, code3, name) VALUES (106,'JM','JAM','Jamaica');
INSERT INTO countries (id, code, code3, name) VALUES (107,'JP','JPN','Japan');
INSERT INTO countries (id, code, code3, name) VALUES (108,'JO','JOR','Jordan');
INSERT INTO countries (id, code, code3, name) VALUES (109,'KZ','KAZ','Kazakhstan');
INSERT INTO countries (id, code, code3, name) VALUES (110,'KE','KEN','Kenya');
INSERT INTO countries (id, code, code3, name) VALUES (111,'KI','KIR','Kiribati');
INSERT INTO countries (id, code, code3, name) VALUES (112,'NK',NULL,'Korea North');
INSERT INTO countries (id, code, code3, name) VALUES (113,'KR','KOR','South Korea');
INSERT INTO countries (id, code, code3, name) VALUES (114,'KW','KWT','Kuwait');
INSERT INTO countries (id, code, code3, name) VALUES (115,'KG','KGZ','Kyrgyzstan');
INSERT INTO countries (id, code, code3, name) VALUES (116,'LA','LAO','Laos');
INSERT INTO countries (id, code, code3, name) VALUES (117,'LV','LVA','Latvia');
INSERT INTO countries (id, code, code3, name) VALUES (118,'LB','LBN','Lebanon');
INSERT INTO countries (id, code, code3, name) VALUES (119,'LS','LSO','Lesotho');
INSERT INTO countries (id, code, code3, name) VALUES (120,'LR','LBR','Liberia');
INSERT INTO countries (id, code, code3, name) VALUES (121,'LY','LBY','Libya');
INSERT INTO countries (id, code, code3, name) VALUES (122,'LI','LIE','Liechtenstein');
INSERT INTO countries (id, code, code3, name) VALUES (123,'LT','LTU','Lithuania');
INSERT INTO countries (id, code, code3, name) VALUES (124,'LU','LUX','Luxembourg');
INSERT INTO countries (id, code, code3, name) VALUES (125,'MO','MAC','Macau');
INSERT INTO countries (id, code, code3, name) VALUES (126,'MK','MKD','Macedonia');
INSERT INTO countries (id, code, code3, name) VALUES (127,'MG','MDG','Madagascar');
INSERT INTO countries (id, code, code3, name) VALUES (128,'MY','MYS','Malaysia');
INSERT INTO countries (id, code, code3, name) VALUES (129,'MW','MWI','Malawi');
INSERT INTO countries (id, code, code3, name) VALUES (130,'MV','MDV','Maldives');
INSERT INTO countries (id, code, code3, name) VALUES (131,'ML','MLI','Mali');
INSERT INTO countries (id, code, code3, name) VALUES (132,'MT','MLT','Malta');
INSERT INTO countries (id, code, code3, name) VALUES (133,'MH','MHL','Marshall Islands');
INSERT INTO countries (id, code, code3, name) VALUES (134,'MQ','MTQ','Martinique');
INSERT INTO countries (id, code, code3, name) VALUES (135,'MR','MRT','Mauritania');
INSERT INTO countries (id, code, code3, name) VALUES (136,'MU','MUS','Mauritius');
INSERT INTO countries (id, code, code3, name) VALUES (137,'MX','MEX','Mexico');
INSERT INTO countries (id, code, code3, name) VALUES (138,'MI',NULL,'Midway Islands');
INSERT INTO countries (id, code, code3, name) VALUES (139,'MD','MDA','Moldova');
INSERT INTO countries (id, code, code3, name) VALUES (140,'MC','MCO','Monaco');
INSERT INTO countries (id, code, code3, name) VALUES (141,'MN','MNG','Mongolia');
INSERT INTO countries (id, code, code3, name) VALUES (142,'MS','MSR','Montserrat');
INSERT INTO countries (id, code, code3, name) VALUES (143,'MA','MAR','Morocco');
INSERT INTO countries (id, code, code3, name) VALUES (144,'MZ','MOZ','Mozambique');
INSERT INTO countries (id, code, code3, name) VALUES (145,'MM','MMR','Myanmar');
INSERT INTO countries (id, code, code3, name) VALUES (146,'NA','NAM','Namibia');
INSERT INTO countries (id, code, code3, name) VALUES (147,'NU','NIU','Nauru');
INSERT INTO countries (id, code, code3, name) VALUES (148,'NP','NPL','Nepal');
INSERT INTO countries (id, code, code3, name) VALUES (149,'AN','ANT','Netherland Antilles');
INSERT INTO countries (id, code, code3, name) VALUES (150,'NL','NLD','Netherlands (Holland, Europe)');
INSERT INTO countries (id, code, code3, name) VALUES (151,'NV',NULL,'Nevis');
INSERT INTO countries (id, code, code3, name) VALUES (152,'NC','NCL','New Caledonia');
INSERT INTO countries (id, code, code3, name) VALUES (153,'NZ','NZL','New Zealand');
INSERT INTO countries (id, code, code3, name) VALUES (154,'NI','NIC','Nicaragua');
INSERT INTO countries (id, code, code3, name) VALUES (155,'NE','NER','Niger');
INSERT INTO countries (id, code, code3, name) VALUES (156,'NG','NGA','Nigeria');
INSERT INTO countries (id, code, code3, name) VALUES (157,'NW',NULL,'Niue');
INSERT INTO countries (id, code, code3, name) VALUES (158,'NF','NFK','Norfolk Island');
INSERT INTO countries (id, code, code3, name) VALUES (159,'NO','NOR','Norway');
INSERT INTO countries (id, code, code3, name) VALUES (160,'OM','OMN','Oman');
INSERT INTO countries (id, code, code3, name) VALUES (161,'PK','PAK','Pakistan');
INSERT INTO countries (id, code, code3, name) VALUES (162,'PW','PLW','Palau Island');
INSERT INTO countries (id, code, code3, name) VALUES (163,'PS','PSE','Palestine');
INSERT INTO countries (id, code, code3, name) VALUES (164,'PA','PAN','Panama');
INSERT INTO countries (id, code, code3, name) VALUES (165,'PG','PNG','Papua New Guinea');
INSERT INTO countries (id, code, code3, name) VALUES (166,'PY','PRY','Paraguay');
INSERT INTO countries (id, code, code3, name) VALUES (167,'PE','PER','Peru');
INSERT INTO countries (id, code, code3, name) VALUES (168,'PH','PHL','Philippines');
INSERT INTO countries (id, code, code3, name) VALUES (169,'PO',NULL,'Pitcairn Island');
INSERT INTO countries (id, code, code3, name) VALUES (170,'PL','POL','Poland');
INSERT INTO countries (id, code, code3, name) VALUES (171,'PT','PRT','Portugal');
INSERT INTO countries (id, code, code3, name) VALUES (172,'PR','PRI','Puerto Rico');
INSERT INTO countries (id, code, code3, name) VALUES (173,'QA','QAT','Qatar');
INSERT INTO countries (id, code, code3, name) VALUES (174,'ME','MNE','Republic of Montenegro');
INSERT INTO countries (id, code, code3, name) VALUES (175,'RS','SRB','Republic of Serbia');
INSERT INTO countries (id, code, code3, name) VALUES (176,'RE','REU','Reunion');
INSERT INTO countries (id, code, code3, name) VALUES (177,'RO','ROU','Romania');
INSERT INTO countries (id, code, code3, name) VALUES (178,'RU','RUS','Russia');
INSERT INTO countries (id, code, code3, name) VALUES (179,'RW','RWA','Rwanda');
INSERT INTO countries (id, code, code3, name) VALUES (180,'BL','BLM','St Barthelemy');
INSERT INTO countries (id, code, code3, name) VALUES (181,'BQ','BES','Bonaire, Sint Eustatius and Saba');
INSERT INTO countries (id, code, code3, name) VALUES (182,'HE',NULL,'St Helena');
INSERT INTO countries (id, code, code3, name) VALUES (183,'KN','KNA','St Kitts-Nevis');
INSERT INTO countries (id, code, code3, name) VALUES (184,'LC','LCA','St Lucia');
INSERT INTO countries (id, code, code3, name) VALUES (185,'SX','SXM','Sint Maarten');
INSERT INTO countries (id, code, code3, name) VALUES (186,'PM','SPM','St Pierre &amp; Miquelon');
INSERT INTO countries (id, code, code3, name) VALUES (187,'VC','VCT','St Vincent &amp; Grenadines');
INSERT INTO countries (id, code, code3, name) VALUES (188,'SP',NULL,'Saipan');
INSERT INTO countries (id, code, code3, name) VALUES (189,'WS','WSM','Samoa');
INSERT INTO countries (id, code, code3, name) VALUES (190,'SM','SMR','San Marino');
INSERT INTO countries (id, code, code3, name) VALUES (191,'ST','STP','Sao Tome &amp; Principe');
INSERT INTO countries (id, code, code3, name) VALUES (192,'SA','SAU','Saudi Arabia');
INSERT INTO countries (id, code, code3, name) VALUES (193,'SN','SEN','Senegal');
INSERT INTO countries (id, code, code3, name) VALUES (194,'SC','SYC','Seychelles');
INSERT INTO countries (id, code, code3, name) VALUES (195,'SL','SLE','Sierra Leone');
INSERT INTO countries (id, code, code3, name) VALUES (196,'SG','SGP','Singapore');
INSERT INTO countries (id, code, code3, name) VALUES (197,'SK','SVK','Slovakia');
INSERT INTO countries (id, code, code3, name) VALUES (198,'SI','SVN','Slovenia');
INSERT INTO countries (id, code, code3, name) VALUES (199,'SB','SLB','Solomon Islands');
INSERT INTO countries (id, code, code3, name) VALUES (200,'SO','SOM','Somalia');
INSERT INTO countries (id, code, code3, name) VALUES (201,'ZA','ZAF','South Africa');
INSERT INTO countries (id, code, code3, name) VALUES (202,'ES','ESP','Spain');
INSERT INTO countries (id, code, code3, name) VALUES (203,'LK','LKA','Sri Lanka');
INSERT INTO countries (id, code, code3, name) VALUES (204,'SD','SDN','Sudan');
INSERT INTO countries (id, code, code3, name) VALUES (205,'SR','SUR','Suriname');
INSERT INTO countries (id, code, code3, name) VALUES (206,'SZ','SWZ','Swaziland');
INSERT INTO countries (id, code, code3, name) VALUES (207,'SE','SWE','Sweden');
INSERT INTO countries (id, code, code3, name) VALUES (208,'CH','CHE','Switzerland');
INSERT INTO countries (id, code, code3, name) VALUES (209,'SY','SYR','Syria');
INSERT INTO countries (id, code, code3, name) VALUES (210,'TA',NULL,'Tahiti');
INSERT INTO countries (id, code, code3, name) VALUES (211,'TW','TWN','Taiwan');
INSERT INTO countries (id, code, code3, name) VALUES (212,'TJ','TJK','Tajikistan');
INSERT INTO countries (id, code, code3, name) VALUES (213,'TZ','TZA','Tanzania');
INSERT INTO countries (id, code, code3, name) VALUES (214,'TH','THA','Thailand');
INSERT INTO countries (id, code, code3, name) VALUES (215,'TG','TGO','Togo');
INSERT INTO countries (id, code, code3, name) VALUES (216,'TK','TKL','Tokelau');
INSERT INTO countries (id, code, code3, name) VALUES (217,'TO','TON','Tonga');
INSERT INTO countries (id, code, code3, name) VALUES (218,'TT','TTO','Trinidad &amp; Tobago');
INSERT INTO countries (id, code, code3, name) VALUES (219,'TN','TUN','Tunisia');
INSERT INTO countries (id, code, code3, name) VALUES (220,'TR','TUR','Turkey');
INSERT INTO countries (id, code, code3, name) VALUES (221,'TU',NULL,'Turkmenistan');
INSERT INTO countries (id, code, code3, name) VALUES (222,'TC','TCA','Turks &amp; Caicos Is');
INSERT INTO countries (id, code, code3, name) VALUES (223,'TV','TUV','Tuvalu');
INSERT INTO countries (id, code, code3, name) VALUES (224,'UG','UGA','Uganda');
INSERT INTO countries (id, code, code3, name) VALUES (225,'UA','UKR','Ukraine');
INSERT INTO countries (id, code, code3, name) VALUES (226,'AE','ARE','United Arab Emirates');
INSERT INTO countries (id, code, code3, name) VALUES (227,'GB','GBR','United Kingdom');
INSERT INTO countries (id, code, code3, name) VALUES (228,'US','USA','United States');
INSERT INTO countries (id, code, code3, name) VALUES (229,'UY','URY','Uruguay');
INSERT INTO countries (id, code, code3, name) VALUES (230,'UZ','UZB','Uzbekistan');
INSERT INTO countries (id, code, code3, name) VALUES (231,'VU','VUT','Vanuatu');
INSERT INTO countries (id, code, code3, name) VALUES (232,'VA','VAT','Vatican City State');
INSERT INTO countries (id, code, code3, name) VALUES (233,'VE','VEN','Venezuela');
INSERT INTO countries (id, code, code3, name) VALUES (234,'VN','VNM','Vietnam');
INSERT INTO countries (id, code, code3, name) VALUES (235,'VG','VGB','British Virgin Islands');
INSERT INTO countries (id, code, code3, name) VALUES (236,'VI','VIR','US Virgin Islands');
INSERT INTO countries (id, code, code3, name) VALUES (237,'WK',NULL,'Wake Island');
INSERT INTO countries (id, code, code3, name) VALUES (238,'WF','WLF','Wallis and Futuna');
INSERT INTO countries (id, code, code3, name) VALUES (239,'YE','YEM','Yemen');
INSERT INTO countries (id, code, code3, name) VALUES (240,'ZR',NULL,'Zaire');
INSERT INTO countries (id, code, code3, name) VALUES (241,'ZM','ZMB','Zambia');
INSERT INTO countries (id, code, code3, name) VALUES (242,'ZW','ZWE','Zimbabwe');
INSERT INTO countries (id, code, code3, name) VALUES (25,'AG','ATG','Antigua and Barbuda');
INSERT INTO countries (id, code, code3, name) VALUES (243,'CD','COD','Democtratic Republic of the Congo');
INSERT INTO countries (id, code, code3, name) VALUES (244,'SS','SSD','South Sudan');
INSERT INTO countries (id, code, code3, name) VALUES (245,'GW','GNB','Guinea-Bissau');
INSERT INTO countries (id, code, code3, name) VALUES (246,'YT','MYT','Mayotte');
INSERT INTO countries (id, code, code3, name) VALUES (247,'EH','ESH','Western Sahara');
INSERT INTO countries (id, code, code3, name) VALUES (248,'MF','MAF','Saint Martin');
