#!/bin/csh -f
# Copyright (c) Ohad Aloni 2020. All rights reserved.
# # Released under http://www.theora.com/license.txt (BSD)

set V=/var/www/vhosts
set TAS=$V/tas.theora.com
set corona=$V/corona.theora.com

source $TAS/conf/dbCredentials.env
set loginArgs=(  -u$M_USER -p$M_PASSWORD )

cd $corona/db

set opts=( --complete-insert --skip-quote-names --lock-tables=FALSE --extended-insert=FALSE )

set db=corona
set file=db.sql

mysqldump $loginArgs $opts $db \
		| fgrep -v 'Dump completed on'\
		| sed 's/AUTO_INCREMENT=[0-9]*//' \
		> $file
git commit -m dbBackup $file |& egrep -v 'On branch master|nothing to commit|master.*dbBackup'
